name: Tag on Push

on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from composer.json
        id: get_version
        run: |
          version=$(jq -r '.version' composer.json)
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Tag version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.get_version.outputs.version }}